#! /bin/bash

# BASIC DATA
## browsers array
    browser[0]="firefox"
    browser[1]="chrome"
    browser[2]="opera"
    browser[3]="w3m"
    browser[4]="links"
    browser[5]="other"

    declare -a browser

## array of browser indexes
    Nb=(0 1 2 3 4 5)
    declare -a Nb

## browsers functions
    function firefox_function(){
        firefox $1 & disown && exit
    }
    function chrome_function(){
        google-chrome $1 & disown && exit
    }
    function opera_function(){
        opera $1 & disown && exit
    }
    function w3m_function(){
        w3m $1
    }
    function links_function(){
        links $1
    }

## array of browser functions
    for i in ${!Nb[@]}; do
        browser_function[$i]=${browser[$i]}_function
    done
    declare -a browser_function

## search enfines array
    search_engine[0]="duckduckgo"
    search_engine[1]="google"
    search_engine[2]="bing"

    declare -a search_engine

## array of search engine indexes
    Ns=(0 1 2)
    declare -a Ns

## search engine functions
    function duckduckgo_function(){
        vars="$1 $2 $3 $4 $5"
        term=${vars// /+}
        search=https://duckduckgo.com?q=$term
    }
    function google_function(){
        vars="$1 $2 $3 $4 $5"
        term=${vars// /+}
        search=https://google.com/search?q=$term
    }
    function bing_function(){
        vars="$1 $2 $3 $4 $5"
        term=${vars// /+}
        search=https://bing.com/search?q=$term
    }

## array of search engine functions
    for i in ${!Ns[@]}; do
        search_engine_function[$i]=${search_engine[$i]}_function
    done
    declare -a search_engine_function

# Config Data
    main_browser=firefox
    main_search_engine=google




